const list_data = [
    {
        name:"victoria secret's love spell",
        price:"5 000",
        cover:"../assets/images/lovespell.png",
        seller:"Darisse",
        seller_cover:"../assets/images/darisse.jpg",
        brand:"Apparel",
        year:"2022",
        quality:"Brand new",
        origin:"USA",
        link:"https://wa.link/wyl9zv",
        details:"Pure Seduction by Victoria's Secret is a Floral Fruity fragrance for women.",
        id:"0"
    },
    {
        name:"64 GB USB",
        price:"4 000",
        cover:"../assets/images/cle.jpg",
        seller:"Djamil Din",
        seller_cover:"../assets/images/din.jpg",
        brand:"faster",
        year:"2019",
        quality:"brand new",
        origin:"China",
        link:"https://wa.link/f0p7rk",
        details:"Faster USB key 64GB 3.0",
        id:"1"
    },
    {
        name:"swiss flower air freshener",
        price:"1 500",
        cover:"../assets/images/swiss flower.png",
        seller:"Darisse",
        seller_cover:"../assets/images/darisse.jpg",
        brand:"swiss air refreshener",
        year:"2020",
        quality:"Brand new",
        origin:"USA",
        link:"https://wa.link/wyl9zv",
        details:"Parfum pour rafraichir l'air ",
        id:"2"
    },

    {
        name:"victoria secret's pure seduction",
        price:"5 000",
        cover:"../assets/images/pureseduction.png",
        seller:"Darisse",
        seller_cover:"../assets/images/darisse.jpg",
        brand:"Apparel",
        year:"2021",
        quality:"Brand new",
        origin:"USA",
        link:"https://wa.link/wyl9zv",
        details:"Pure Seduction by Victoria's Secret is a Floral Fruity fragrance for women.",
        id:"3"
    },
    {
        name:"Desktop core i5",
        price:"75 000",
        cover:"../assets/images/dell.png",
        seller:"Djamil Din",
        seller_cover:"../assets/images/din.jpg",
        brand:"Dell",
        year:"2019",
        quality:"used like new",
        origin:"Canada",
        link:"https://wa.link/f0p7rk",
        details:"Dell Optiplex 9010 core i5 4th gen 8GB ram, 500GB hdd, Monitor 24 inches",
        id:"4"
    },

    {
        name:"facial cleaning brush",
        price:"3 500",
        cover:"../assets/images/beryl.png",
        seller:"Darisse",
        seller_cover:"../assets/images/darisse.jpg",
        brand:"Daryl",
        year:"2020",
        quality:"Brand new",
        origin:"USA",
        link:"https://wa.link/wyl9zv",
        details:"Brosse de nettoyage du visage rotative électrique, nettoyeur ultrasonique étanche, livres profonds, extinction de la peau, 3 en 1",
        id:"5"
    },

    {
        name:"imac 21 inches 2015",
        price:"125 000",
        cover:"../assets/images/imac.png",
        seller:"Djamil Din",
        seller_cover:"../assets/images/din.jpg",
        brand:"Apple",
        year:"2015",
        quality:"used like new",
        origin:"USA",
        link:"https://wa.link/f0p7rk",
        details:"imac core i5 late 2015 8GB ram, 1TB hdd screen 21 inches",
        id:"6"
    },
]